apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: prom/prometheus
    version: "{APP_VERSION}"
  name: easynvest-prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prom/prometheus
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: prom/prometheus
        version: "{APP_VERSION}"
    spec:
      containers:
      - image: {APP_IMAGE}
        imagePullPolicy: Always
        name: easynvest-prometheus
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

