apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: easynvest-prometheus
  namespace: monitoring
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: easynvest-prometheus
  targetCPUUtilizationPercentage: 50

